# -*- coding: utf-8 -*-
"""Q1_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qS8-5c3lwMfeY1LGlMIEVk-f-5K2bDZC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from linearRegression.linear_regression import LinearRegression
from metrics import *
import time
np.random.seed(45)

N = 500000
P = 65
X = pd.DataFrame(np.random.randn(N, P))
y = pd.Series(np.random.randn(N))
print(X.shape)


#Evaluating sklearn's implementation of linear regression
mean_arr=[]
for i in range(10):
    t1=time.time()
    LR = LinearRegression(fit_intercept=True)
    LR.fit_sklearn_LR(X,y)
    t2=time.time()
    sklearn_time=t2-t1
    mean_arr.append(sklearn_time)

y_hat = LR.predict(X)

print('For sklearn LinearRegression : \n')
print('RMSE: ', rmse(y_hat, y))
print('MAE: ', mae(y_hat, y))
print("MSE: ", LR.mse_loss(X, y))
print(np.mean(np.array(mean_arr)),"Sklearn mean time ")
print("---------------------------")

#Evaluating solution of linear regression using normal equations
mean_arr=[]
for i in range(10):

    t1=time.time()
    LR = LinearRegression(fit_intercept=True)
    LR.fit_normal_equations(X,y)
    t2=time.time()
    normal_time=t2-t1
    y_hat = LR.predict(X)
    mean_arr.append(normal_time)

print('For linear regression using normal equations : \n')
print('RMSE: ', rmse(y_hat, y))
print('MAE: ', mae(y_hat, y))
print("MSE: ", LR.mse_loss(X, y))
print(np.mean(np.array(mean_arr)),"Normal equation time ")

print("---------------------------")
#Evaluating solution of linear regression using SVD
mean_arr=[]
for i in range(10):

    t1=time.time()
    LR = LinearRegression(fit_intercept=True)
    LR.fit_SVD(X,y)
    t2=time.time()
    svd_time=t2-t1
    y_hat = LR.predict(X)
    mean_arr.append(svd_time)

print('For linear regression using SVD : \n')
print('RMSE: ', rmse(y_hat, y))
print('MAE: ', mae(y_hat, y))
print("MSE: ", LR.mse_loss(X, y))
print(np.mean(np.array(mean_arr)),"SVD mean time ")
print("---------------------------")
